### ISSUE TITLE
{NOT A BUG, just a dumb feature request} can you please add RDR1 mousehook support?

### ISSUE THREAD

**Issue by dsmirc** [marinesciencedude/xenia-canary-mousehook#17]
Firstly, I'd like to express my gratitude for your continued work on the mousehook script originally created by emoose. I thoroughly enjoyed using it while playing Halo 3. However, could you kindly consider adding mousehook support to Red Dead Redemption? Currently, there isn't an optimal way to enjoy the game with mouse and keyboard controls. As always, thank you for your dedication to improving this project.

**Comment by marinesciencedude** [comment]
Yes, Red Dead Redemption *is* planned in future, I can't give an ETA because I want to finish up on Minecraft and then it might take some time to get the ball rolling with finding the addresses to hook to but I should be letting people know it's definitely on the roadmap.

Also don't worry about putting feature requests in issues, basically what everyone everywhere else uses it for anyway.

**Comment by Clippy95** [comment]
https://github.com/DottierGalaxy50/rdr-pc-controls-xenia
There is this cheat table with all addresses required for mousehook, it only works this [version](https://github.com/xenia-canary/xenia-canary/releases/tag/ec267c3) of Xenia Canary

**Comment by marinesciencedude** [comment]
Currently being developed at https://github.com/Clippy95/xenia-canary-mousehook/tree/RDR, should be merged in the near future.
